import Link from "next/link";
import { CAPABILITIES } from "@/lib/auth/capabilities";
import { getAdminContext } from "@/lib/auth/admin-context";
import { agendaLookbackIso } from "@/lib/time";
import { createDiscipline, createSession, createTemplate } from "./actions";

function formatDateTime(value: string, timeZone: string) {
  return new Intl.DateTimeFormat("es-MX", { timeZone, weekday: "short", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}

export default async function AgendaPage({ searchParams }: { searchParams: Promise<{ error?: string; created?: string }> }) {
  const params = await searchParams; const { supabase, studio, can } = await getAdminContext(CAPABILITIES.SCHEDULE_READ); const canEdit = can(CAPABILITIES.SCHEDULE_WRITE);
  const [{ data: disciplines }, { data: templates }, { data: spaces }, { data: instructors }, { data: persons }, { data: sessions }] = await Promise.all([
    supabase.from("disciplines").select("id, name, active").eq("studio_id", studio.id).order("name"),
    supabase.from("class_templates").select("id, name, duration_minutes, capacity, discipline_id").eq("studio_id", studio.id).eq("active", true).order("name"),
    supabase.from("spaces").select("id, name, capacity, site_id").eq("studio_id", studio.id).eq("active", true).order("name"),
    supabase.from("instructors").select("id, person_id, status").eq("studio_id", studio.id).eq("status", "active"),
    supabase.from("persons").select("id, first_name, last_name").eq("studio_id", studio.id),
    supabase.from("class_sessions").select("id, starts_at, ends_at, capacity, status, notes, template_id, space_id, instructor_id").eq("studio_id", studio.id).gte("starts_at", agendaLookbackIso()).order("starts_at", { ascending: true }).limit(60),
  ]);
  const disciplineMap = new Map((disciplines ?? []).map((item) => [item.id, item.name])); const templateMap = new Map((templates ?? []).map((item) => [item.id, item])); const spaceMap = new Map((spaces ?? []).map((item) => [item.id, item.name])); const personMap = new Map((persons ?? []).map((item) => [item.id, [item.first_name, item.last_name].filter(Boolean).join(" ")])); const instructorMap = new Map((instructors ?? []).map((item) => [item.id, personMap.get(item.person_id) ?? "Instructor"])); const timeZone = studio.timezone ?? "America/Mexico_City";
  const errorCopy: Record<string, string> = { conflict: "El instructor o espacio ya está ocupado en uno de los horarios.", space: "El espacio no es válido o su capacidad es menor al cupo de la clase.", instructor: "Selecciona un instructor activo del estudio." };
  return <main className="dashboard-shell"><header className="topbar"><div><Link className="back-link compact" href="/admin">← Hoy</Link><p className="eyebrow">AGENDA · {studio.name}</p><h1 className="dashboard-title">Calendario</h1><p>Disciplinas, actividades y sesiones reales del estudio.</p></div></header>
    {params.created ? <div className="notice success">{params.created === "series" ? "Serie semanal programada correctamente." : "Cambio guardado correctamente."}</div> : null}{params.error ? <div className="notice error">{errorCopy[params.error] ?? "No se pudo guardar. Revisa los datos e inténtalo de nuevo."}</div> : null}
    <section className="agenda-layout"><div className="agenda-main"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">PRÓXIMAS SESIONES</p><h2>Clases programadas</h2></div><span className="count-badge">{sessions?.length ?? 0}</span></div>{(sessions?.length ?? 0) === 0 ? <div className="empty-state">Aún no hay sesiones programadas.</div> : <div className="session-list">{sessions?.map((session) => { const template = templateMap.get(session.template_id); return <Link className="session-row" href={`/admin/agenda/${session.id}`} key={session.id}><div className="session-time"><strong>{formatDateTime(session.starts_at, timeZone)}</strong><span>{formatDateTime(session.ends_at, timeZone).split(",").pop()?.trim()}</span></div><div className="session-copy"><strong>{template?.name ?? "Clase"}</strong><span>{template ? disciplineMap.get(template.discipline_id) : "Sin disciplina"} · {session.space_id ? (spaceMap.get(session.space_id) ?? "Espacio") : "Sin espacio"} · {session.instructor_id ? (instructorMap.get(session.instructor_id) ?? "Instructor") : "Sin instructor"}</span></div><div className="session-meta"><span>{session.capacity} lugares</span><span className="status-pill">{session.status}</span></div></Link>; })}</div>}</article></div>
    <aside className="agenda-sidebar">{!canEdit ? <article className="panel"><p>Puedes consultar la agenda, pero no tienes permiso para modificarla.</p></article> : <><article className="panel compact-panel"><p className="eyebrow">1 · DISCIPLINA</p><h2>Nueva disciplina</h2><form action={createDiscipline} className="compact-form"><input name="name" required placeholder="Ej. Pole Fitness"/><button className="primary-button" type="submit">Agregar</button></form></article>
      <article className="panel compact-panel"><p className="eyebrow">2 · ACTIVIDAD</p><h2>Nuevo tipo de clase</h2><form action={createTemplate} className="compact-form"><input name="name" required placeholder="Ej. Pole Fitness Básico"/><select name="discipline_id" required defaultValue=""><option value="" disabled>Disciplina</option>{disciplines?.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="form-split"><input name="duration_minutes" type="number" min="15" max="360" defaultValue="60" required aria-label="Duración en minutos"/><input name="capacity" type="number" min="1" defaultValue="8" required aria-label="Capacidad"/></div><button className="primary-button" type="submit" disabled={!disciplines?.length}>Crear actividad</button></form></article>
      <article className="panel compact-panel"><p className="eyebrow">3 · SESIÓN</p><h2>Programar clase</h2><form action={createSession} className="compact-form"><select name="template_id" required defaultValue=""><option value="" disabled>Actividad</option>{templates?.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.duration_minutes} min</option>)}</select><select name="instructor_id" defaultValue=""><option value="">Sin instructor</option>{instructors?.map((item) => <option key={item.id} value={item.id}>{personMap.get(item.person_id) ?? "Instructor"}</option>)}</select><select name="space_id" defaultValue={spaces?.[0]?.id ?? ""}><option value="">Sin espacio</option>{spaces?.map((item) => <option key={item.id} value={item.id}>{item.name}{item.capacity ? ` · máx. ${item.capacity}` : ""}</option>)}</select><input name="capacity" type="number" min="1" defaultValue="8" required aria-label="Cupo de la sesión"/><input name="starts_at" type="datetime-local" required aria-label="Fecha y hora"/><label>Repetición semanal<select name="repeat_weeks" defaultValue="1"><option value="1">Solo esta clase</option><option value="4">4 semanas</option><option value="8">8 semanas</option><option value="12">12 semanas</option></select></label><textarea name="notes" rows={3} placeholder="Notas opcionales"/><button className="primary-button" type="submit" disabled={!templates?.length}>Programar clase</button></form></article></>}</aside></section></main>;
}
