begin;
set local request.jwt.claim.role='service_role';
set local request.jwt.claims='{"role":"service_role"}';
do $uat$
declare source uuid:='9fe23cfa-fb47-4670-afeb-ed4a56433772'; owner uuid; r jsonb; s uuid; student uuid; c uuid:=gen_random_uuid(); key uuid:=gen_random_uuid(); product uuid; price integer; result jsonb; sale uuid; acquisition uuid; session uuid; alt uuid; reservation uuid; first_date date; expiry date; h uuid; outcomes jsonb:='[]';
begin
 select user_id into owner from public.studio_memberships where studio_id=source and active and role='owner' limit 1;
 r:=public.service_create_demi_uat_run(source,owner,'cash-human-uat'); s:=(r->>'studio_id')::uuid;
 student:=(r#>>'{fixtures,people,student_cash,student_id}')::uuid;
 product:=(r#>>'{fixtures,products,package}')::uuid;
 select price_minor into price from public.product_templates where id=product and studio_id=s;
 insert into public.assistant_conversations(id,studio_id,student_id,channel) values(c,s,student,'internal_demo');
 result:=public.service_create_demi_cash_purchase(s,c,student,product,key,price);
 if not coalesce((result->>'ok')::boolean,false) then raise exception 'cash_create:%',result; end if;
 sale:=(result->>'sale_id')::uuid; acquisition:=(result->>'acquisition_id')::uuid;
 if exists(select 1 from public.payments where sale_id=sale) or exists(select 1 from public.product_acquisitions where id=acquisition and (starts_on is not null or expires_on is not null)) then raise exception 'cash_fake_payment_or_activation'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M13','variant','cash_debt_without_fake_payment_or_start','passed',true));
 result:=public.service_create_demi_cash_purchase(s,c,student,product,key,price);
 if not coalesce((result->>'idempotent')::boolean,false) or (select count(*) from public.demi_cash_purchases where studio_id=s and student_id=student)<>1 then raise exception 'cash_replay:%',result; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M13','variant','cash_sale_idempotent','passed',true));
 session:=(r#>>'{fixtures,sessions,available}')::uuid; alt:=(r#>>'{fixtures,sessions,alternative}')::uuid;
 result:=public.service_book_student(s,session,student);
 if not coalesce((result->>'eligible')::boolean,false) then raise exception 'cash_first_booking:%',result; end if;
 select id into reservation from public.reservations where studio_id=s and student_id=student and session_id=session and status='reserved';
 select (cs.starts_at at time zone st.timezone)::date into first_date from public.class_sessions cs join public.studios st on st.id=cs.studio_id where cs.id=session;
 select expires_on into expiry from public.product_acquisitions where id=acquisition and starts_on=first_date;
 if expiry is null then raise exception 'cash_first_date_not_activated'; end if;
 result:=public.service_book_student(s,alt,student);
 if result->>'reason_code'<>'payment_pending' or exists(select 1 from public.reservations where studio_id=s and student_id=student and session_id=alt) then raise exception 'cash_second_booking:%',result; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M13','variant','first_booking_starts_validity_second_blocked_until_collection','passed',true));
 perform set_config('request.jwt.claim.sub',owner::text,true); perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',owner)::text,true);
 perform public.register_sale_payment(sale,price,'cash','UAT ficticio', 'Cobro ficticio real en tabla, rollback');
 if (select coalesce(sum(amount_minor),0) from public.payments where sale_id=sale and kind='payment')<>price then raise exception 'cash_collection_missing'; end if;
 result:=public.service_book_student(s,alt,student);
 if not coalesce((result->>'eligible')::boolean,false) then raise exception 'cash_booking_after_collection:%',result; end if;
 if not exists(select 1 from public.product_acquisitions where id=acquisition and starts_on=first_date and expires_on=expiry) then raise exception 'cash_validity_reset'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M13','variant','actual_collection_unlocks_second_booking_without_reset','passed',true));
 result:=public.assistant_create_handoff(s,c,student,'user_requested','UAT tomar y devolver control');
 select id into h from public.assistant_handoffs where studio_id=s and conversation_id=c and status='open' limit 1;
 result:=public.admin_claim_demi_handoff(s,h);
 if not coalesce((result->>'ok')::boolean,false) or not exists(select 1 from public.assistant_conversations where id=c and context->>'human_takeover'='true') then raise exception 'human_claim:%',result; end if;
 result:=public.admin_resolve_demi_handoff(s,h,'');
 if result->>'reason_code'<>'resolution_note_required' then raise exception 'human_empty_resolution:%',result; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M17','variant','takeover_persisted_resolution_required','passed',true));
 result:=public.admin_resolve_demi_handoff(s,h,'Resuelto en prueba sin envío externo');
 if not coalesce((result->>'automatic_control_returned')::boolean,false) or exists(select 1 from public.assistant_conversations where id=c and context->>'human_takeover'='true') then raise exception 'human_release:%',result; end if;
 result:=public.admin_resolve_demi_handoff(s,h,'Repetición de resolución');
 if not coalesce((result->>'idempotent')::boolean,false) then raise exception 'human_replay:%',result; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M17','variant','resolution_returns_control_idempotently','passed',true));
 perform set_config('uat.cash_human',outcomes::text,true);
end; $uat$;
select current_setting('uat.cash_human')::jsonb as results;
rollback;
