-- Execute only in hedouonyhynuvwbckdlg. Synthetic tenant; all writes rolled back.
begin;
set local role service_role;
set local request.jwt.claim.role='service_role';
set local request.jwt.claims='{"role":"service_role"}';
do $uat$
declare
 source uuid := '9fe23cfa-fb47-4670-afeb-ed4a56433772'; owner uuid;
 run jsonb; s uuid; student uuid; session uuid; acquisition uuid; reservation uuid;
 result jsonb; replay jsonb; outcomes jsonb := '[]'; balance integer; initial_balance integer;
 conversation uuid := gen_random_uuid(); event uuid := gen_random_uuid(); identity jsonb; intent uuid;
begin
 select user_id into owner from public.studio_memberships where studio_id=source and active and role='owner' limit 1;
 run:=public.service_create_demi_uat_run(source,owner,'demi-2-integration'); s:=(run->>'studio_id')::uuid;
 if s=source then raise exception 'isolation_failed'; end if;
 student:=(run#>>'{fixtures,people,student_active,student_id}')::uuid;
 session:=(run#>>'{fixtures,sessions,available}')::uuid;
 select id into acquisition from public.product_acquisitions where studio_id=s and student_id=student;
 select coalesce(sum(quantity),0) into initial_balance from public.credit_ledger where acquisition_id=acquisition;
 result:=public.service_book_student(s,session,student);
 if not coalesce((result->>'eligible')::boolean,false) then raise exception 'M13_booking:%',result; end if;
 select id into reservation from public.reservations where studio_id=s and student_id=student and session_id=session and status='reserved';
 select coalesce(sum(quantity),0) into balance from public.credit_ledger where acquisition_id=acquisition;
 if reservation is null or balance<>initial_balance-1 then raise exception 'M13_credit:%',balance; end if;
 replay:=public.service_book_student(s,session,student);
 if (select count(*) from public.reservations where studio_id=s and student_id=student and session_id=session and status='reserved')<>1 then raise exception 'M13_duplicate'; end if;
 if (select coalesce(sum(quantity),0) from public.credit_ledger where acquisition_id=acquisition)<>balance then raise exception 'M13_double_credit'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M13','variant','booking_and_duplicate','passed',true));
 update public.class_sessions set starts_at=now()+interval '5 hours',ends_at=now()+interval '6 hours' where id=session;
 result:=public.service_cancel_reservation(s,student,reservation,'UAT exact cutoff');
 if not coalesce((result->>'ok')::boolean,false) then raise exception 'M10_cancel:%',result; end if;
 if (select status::text from public.reservations where id=reservation)<>'cancelled_on_time' then raise exception 'M10_exact_cutoff:%',result; end if;
 if (select coalesce(sum(quantity),0) from public.credit_ledger where acquisition_id=acquisition)<>initial_balance then raise exception 'M10_release'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M10','variant','exact_5_hours_credit_restored','passed',true));
 session:=(run#>>'{fixtures,sessions,late}')::uuid;
 result:=public.service_book_student(s,session,student);
 select id into reservation from public.reservations where studio_id=s and student_id=student and session_id=session and status='reserved';
 if reservation is null then raise exception 'M10_late_setup:%',result; end if;
 result:=public.service_cancel_reservation(s,student,reservation,'UAT late');
 if (select status::text from public.reservations where id=reservation)<>'cancelled_late' then raise exception 'M10_late:%',result; end if;
 if (select coalesce(sum(quantity),0) from public.credit_ledger where acquisition_id=acquisition)<>initial_balance-1 then raise exception 'M10_late_credit'; end if;
 replay:=public.service_cancel_reservation(s,student,reservation,'UAT replay');
 if (select coalesce(sum(quantity),0) from public.credit_ledger where acquisition_id=acquisition)<>initial_balance-1 then raise exception 'M10_double_consume'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M10','variant','late_consumed_once','passed',true));
 student:=(run#>>'{fixtures,people,former_active_package,student_id}')::uuid;
 session:=(run#>>'{fixtures,sessions,alternative}')::uuid;
 select id into acquisition from public.product_acquisitions where studio_id=s and student_id=student;
 select coalesce(sum(quantity),0) into initial_balance from public.credit_ledger where acquisition_id=acquisition;
 result:=public.service_book_student(s,session,student);
 if coalesce((result->>'eligible')::boolean,false) or exists(select 1 from public.reservations where studio_id=s and student_id=student) then raise exception 'M15_enrollment_block:%',result; end if;
 if (select coalesce(sum(quantity),0) from public.credit_ledger where acquisition_id=acquisition)<>initial_balance then raise exception 'M15_package_changed'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M15','variant','expired_enrollment_preserves_package','passed',true,'result',result));
 update public.student_enrollments set expires_on=current_date+365 where studio_id=s and student_id=student;
 result:=public.service_book_student(s,session,student);
 if not coalesce((result->>'eligible')::boolean,false) then raise exception 'M16_renewal:%',result; end if;
 if (select coalesce(sum(quantity),0) from public.credit_ledger where acquisition_id=acquisition)<>initial_balance-1 then raise exception 'M16_credit'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M16','variant','rights_after_renewal','passed',true));
 insert into public.assistant_conversations(id,studio_id,student_id,channel) values(conversation,s,student,'internal_demo');
 result:=public.assistant_create_handoff(s,conversation,student,'user_requested','Solicitud ficticia UAT');
 if not coalesce((result->>'ok')::boolean,false) or not exists(select 1 from public.assistant_handoffs where studio_id=s and conversation_id=conversation) then raise exception 'M17_handoff:%',result; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M17','variant','persistent_human_case','passed',true));
 update public.demi_uat_runs set faults='{"delivery_failures_remaining":3}' where id=(run->>'id')::uuid;
 for balance in 1..3 loop
  result:=public.service_capture_demi_uat_delivery(s,'uat-retry',jsonb_build_object('attempt',balance));
  if not coalesce((result->>'failed')::boolean,false) then raise exception 'M09_fault:%',balance; end if;
 end loop;
 result:=public.service_capture_demi_uat_delivery(s,'uat-retry','{"attempt":4}');
 if coalesce((result->>'failed')::boolean,false) then raise exception 'M09_counter'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M09','variant','three_captured_delivery_failures','passed',true));
 perform set_config('request.jwt.claim.sub',owner::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',owner)::text,true);
 student:=(run#>>'{fixtures,people,student_active,student_id}')::uuid;
 session:=(run#>>'{fixtures,sessions,alternative}')::uuid;
 select id into acquisition from public.product_acquisitions where studio_id=s and student_id=student;
 select coalesce(sum(quantity),0) into initial_balance from public.credit_ledger where acquisition_id=acquisition;
 result:=public.service_book_student(s,session,student);
 select id into reservation from public.reservations where studio_id=s and student_id=student and session_id=session and status='reserved';
 if reservation is null then raise exception 'M13_no_show_setup:%',result; end if;
 update public.class_sessions set starts_at=now()-interval '10 minutes',ends_at=now()+interval '50 minutes' where id=session;
 result:=public.set_attendance_status(reservation,'no_show','UAT absence');
 if not coalesce((result->>'ok')::boolean,false) then raise exception 'M13_no_show:%',result; end if;
 if (select coalesce(sum(quantity),0) from public.credit_ledger where acquisition_id=acquisition)<>initial_balance-1 then raise exception 'M13_absence_credit'; end if;
 result:=public.set_attendance_status(reservation,'no_show','UAT absence replay');
 if (select coalesce(sum(quantity),0) from public.credit_ledger where acquisition_id=acquisition)<>initial_balance-1 then raise exception 'M13_absence_double_credit'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M13','variant','no_show_consumed_once','passed',true));
 -- Attendance uses the regular authenticated admin RPC and a class in progress.
 student:=(run#>>'{fixtures,people,trial_reserved,student_id}')::uuid;
 select id,session_id,acquisition_id into reservation,session,acquisition from public.reservations where studio_id=s and student_id=student and status='reserved';
 update public.class_sessions set starts_at=now()-interval '10 minutes',ends_at=now()+interval '50 minutes' where id=session;
 result:=public.set_attendance_status(reservation,'attended','UAT trial attendance');
 if not coalesce((result->>'ok')::boolean,false) then raise exception 'M11_attendance:%',result; end if;
 if (select student_type::text from public.students where id=student)<>'trial' then raise exception 'M11_premature_conversion'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M11','variant','attended_stays_trial','passed',true));
 -- Create a receipt-backed trial and reject it with the real review RPC.
 student:=(run#>>'{fixtures,people,trial_cancelled,student_id}')::uuid;
 session:=(run#>>'{fixtures,sessions,available}')::uuid;
 conversation:=gen_random_uuid();
 insert into public.assistant_conversations(id,studio_id,student_id,channel) values(conversation,s,student,'internal_demo');
 result:=public.service_prepare_trial_transfer(s,conversation,student,session,null);
 if not coalesce((result->>'ok')::boolean,false) then raise exception 'M12_prepare:%',result; end if;
 intent:=(result->>'intent_id')::uuid;
 insert into public.assistant_whatsapp_events(id,studio_id,provider,provider_event_id,phone_number_id,contact_wa_id,message_type,media_id,payload_fingerprint)
 values(event,s,'meta_whatsapp','uat-'||event,'internal_demo','internal_demo:'||student,'image','uat-media','uat-fingerprint');
 update public.assistant_transfer_purchase_intents set receipt_amount_matches=true,receipt_detected_amount_minor=15000,receipt_detected_currency='MXN',receipt_read_confidence=0.99,receipt_storage_path='UAT/fictional.png' where id=intent;
 result:=public.service_activate_trial_transfer_receipt(s,conversation,student,intent,event,'uat-'||event,'uat-media');
 if not coalesce((result->>'ok')::boolean,false) then raise exception 'M12_activate:%',result; end if;
 reservation:=(result->>'reservation_id')::uuid;
 execute 'set local role authenticated';
 perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',owner)::text,true);
 result:=public.admin_review_transfer_purchase(intent,'rejected','Rechazo ficticio UAT');
 if not coalesce((result->>'ok')::boolean,false) or (select status from public.assistant_transfer_purchase_intents where id=intent)<>'rejected' then raise exception 'M12_review:%',result; end if;
 if (select status::text from public.reservations where id=reservation)='reserved' then raise exception 'M12_reservation_not_revoked'; end if;
 if not exists(select 1 from public.reservations where id=reservation) then raise exception 'M12_history_deleted'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M12','variant','trial_receipt_rejected_reservation_revoked','passed',true));
 perform set_config('uat.demi_2_results',outcomes::text,true);
end;
$uat$;
select current_setting('uat.demi_2_results')::jsonb as results;
rollback;
