begin;
set local request.jwt.claim.role='service_role';
set local request.jwt.claims='{"role":"service_role"}';
do $$
declare source uuid:='9fe23cfa-fb47-4670-afeb-ed4a56433772'; actor uuid; run jsonb; s uuid; c uuid:=gen_random_uuid(); event uuid:=gen_random_uuid(); session uuid; g uuid; r jsonb; out jsonb:='[]'; a uuid; student uuid; reservation uuid; starts date; expiry date; target uuid; people jsonb:='[{"name":"UAT Grupo Uno","phone":"9998880001"},{"name":"UAT Grupo Dos","phone":"9998880002"}]';
begin
 select user_id into actor from public.studio_memberships where studio_id=source and active and role='owner' limit 1;
 run:=public.service_create_demi_uat_run(source,actor,'group-uat');s:=(run->>'studio_id')::uuid;session:=(run#>>'{fixtures,sessions,available}')::uuid;
 insert into public.assistant_conversations(id,studio_id,channel) values(c,s,'internal_demo');
 r:=public.service_prepare_demi_group(s,c,session,2,2);
 if not coalesce((r->>'ok')::boolean,false) or (r->>'amount_minor')::integer<>30000 then raise exception 'group_prepare:%',r; end if;
 g:=(r->>'group_id')::uuid;
 r:=public.service_complete_demi_group(s,c,g,people);
 if r->>'reason_code'<>'receipt_required_before_participants' then raise exception 'payment_first:%',r; end if;
 if exists(select 1 from public.students where studio_id=s and phone in ('+529998880001','+529998880002')) then raise exception 'profile_before_proof'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','payment_first_no_profiles','passed',true));
 insert into public.assistant_whatsapp_events(id,studio_id,provider,provider_event_id,phone_number_id,contact_wa_id,message_type,media_id,payload_fingerprint)
 values(event,s,'meta_whatsapp','group-'||event,'uat','99900000000','image','group-media','group-uat');
 r:=public.service_record_demi_group_receipt(s,c,g,event,'group-'||event,'group-media','UAT/group.png',repeat('a',64),15000,'MXN',0.99);
 if r->>'reason_code'<>'receipt_amount_mismatch' then raise exception 'group_amount:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','partial_amount_blocked','passed',true));
 r:=public.service_record_demi_group_receipt(s,c,g,event,'group-'||event,'group-media','UAT/group.png',repeat('a',64),30000,'MXN',0.99);
 if not coalesce((r->>'ok')::boolean,false) then raise exception 'group_receipt:%',r; end if;
 r:=public.service_complete_demi_group(s,c,g,people);
 if not coalesce((r->>'ok')::boolean,false) or (r->>'reserved_count')::integer<>2 then raise exception 'group_complete:%',r; end if;
 if (select count(*) from public.demi_group_participants where group_id=g and reservation_id is not null)<>2 then raise exception 'group_reservations'; end if;
 if (select sum(total_minor) from public.sales where studio_id=s)<>30000 then raise exception 'group_total_duplicated'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','two_profiles_reservations_single_allocation','passed',true));
 r:=public.service_complete_demi_group(s,c,g,people);
 if not coalesce((r->>'ok')::boolean,false) or (select sum(total_minor) from public.sales where studio_id=s)<>30000 then raise exception 'group_replay:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','completion_idempotent','passed',true));
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',actor)::text,true);
 r:=public.admin_review_demi_group(g,'approved','UAT proof review');
 if not coalesce((r->>'ok')::boolean,false) or (select sum(amount_minor) from public.payments where studio_id=s)<>30000 then raise exception 'group_review:%',r; end if;
 r:=public.admin_review_demi_group(g,'approved','UAT replay');
 if (select sum(amount_minor) from public.payments where studio_id=s)<>30000 then raise exception 'group_double_payment'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','review_allocations_once','passed',true));

 r:=public.service_complete_demi_group(s,c,g,people);
 if r->>'status'<>'validated' or (select status from public.demi_group_bookings where id=g)<>'validated' then raise exception 'validated_replay_regression:%',r; end if;
 select gp.student_id,gp.reservation_id,ti.acquisition_id into student,reservation,a from public.demi_group_participants gp join public.assistant_transfer_purchase_intents ti on ti.id=gp.transfer_intent_id where gp.group_id=g and gp.ordinal=1;
 select starts_on,expires_on into starts,expiry from public.product_acquisitions where id=a;
 if a is null or expiry<>starts+7 or starts<>(select (cs.starts_at at time zone st.timezone)::date from public.class_sessions cs join public.studios st on st.id=cs.studio_id where cs.id=session) then raise exception 'trial_dates:% % %',a,starts,expiry; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M10','variant','trial_credit_first_class_anchor','passed',true));
 r:=public.service_cancel_reservation(s,student,reservation,'UAT paid trial cancel');
 if not coalesce((r->>'ok')::boolean,false) or (select sum(quantity) from public.credit_ledger where acquisition_id=a)<>1 then raise exception 'trial_credit_cancel:%',r; end if;
 target:=(run#>>'{fixtures,sessions,alternative}')::uuid;
 r:=public.service_book_student(s,target,student);
 if not coalesce((r->>'eligible')::boolean,false) then raise exception 'trial_credit_rebook:%',r; end if;
 if (select expires_on from public.product_acquisitions where id=a)<>expiry then raise exception 'trial_expiry_reset'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M10','variant','paid_trial_rebook_preserves_expiry','passed',true));
 select id into reservation from public.reservations where studio_id=s and student_id=student and session_id=target and status='reserved';
 r:=public.service_reschedule_student_reservation(s,student,reservation,session,'UAT paid trial reschedule');
 if not coalesce((r->>'ok')::boolean,false) then raise exception 'trial_credit_reschedule:%',r; end if;
 if (select expires_on from public.product_acquisitions where id=a)<>expiry then raise exception 'reschedule_trial_reset'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M10','variant','paid_trial_reschedule_preserves_expiry','passed',true));
 select id into reservation from public.reservations where studio_id=s and student_id=student and session_id=session and status='reserved';
 r:=public.service_cancel_reservation(s,student,reservation,'UAT cancel again');
 update public.class_sessions set starts_at=starts_at+interval '10 days',ends_at=ends_at+interval '10 days' where id=target;
 r:=public.service_book_student(s,target,student);
 if coalesce((r->>'eligible')::boolean,false) then raise exception 'expired_trial_allowed:%',r; end if;
 if (select expires_on from public.product_acquisitions where id=a)<>expiry then raise exception 'expired_trial_reset'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M10','variant','paid_trial_after_expiry_blocked','passed',true));
 perform set_config('uat.group_results',out::text,true);
end $$;
select current_setting('uat.group_results')::jsonb as results;
rollback;
