begin;
set local role service_role;
set local request.jwt.claim.role='service_role';
set local request.jwt.claims='{"role":"service_role"}';
do $$
declare source uuid:='9fe23cfa-fb47-4670-afeb-ed4a56433772'; actor uuid; run jsonb; s uuid; c uuid:=gen_random_uuid(); event uuid:=gen_random_uuid(); session uuid; g uuid; r jsonb; out jsonb:='[]'; people jsonb:='[{"name":"UAT Grupo Uno","phone":"9998880001"},{"name":"UAT Grupo Dos","phone":"9998880002"}]';
begin
 select user_id into actor from public.studio_memberships where studio_id=source and active and role='owner' limit 1;
 run:=public.service_create_demi_uat_run(source,actor,'group-uat');s:=(run->>'studio_id')::uuid;session:=(run#>>'{fixtures,sessions,available}')::uuid;
 insert into public.assistant_conversations(id,studio_id,channel) values(c,s,'internal_demo');
 r:=public.service_prepare_demi_group(s,c,session,2,2);
 if not coalesce((r->>'ok')::boolean,false) or (r->>'amount_minor')::integer<>30000 then raise exception 'group_prepare:%',r; end if;
 g:=(r->>'group_id')::uuid;
 r:=public.service_complete_demi_group(s,c,g,people);
 if r->>'reason_code'<>'receipt_required_before_participants' then raise exception 'payment_first:%',r; end if;
 if exists(select 1 from public.students where studio_id=s and phone in ('+529998880001','+529998880002')) then raise exception 'profile_before_proof'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','payment_first_no_profiles','passed',true));
 insert into public.assistant_whatsapp_events(id,studio_id,provider,provider_event_id,phone_number_id,contact_wa_id,message_type,media_id,payload_fingerprint)
 values(event,s,'meta_whatsapp','group-'||event,'uat','99900000000','image','group-media','group-uat');
 r:=public.service_record_demi_group_receipt(s,c,g,event,'group-'||event,'group-media','UAT/unreadable.png',repeat('f',64),null,null,0);
 if r->>'reason_code'<>'receipt_unreadable' or not exists(select 1 from public.demi_group_receipts where event_id=event and status='unreadable') then raise exception 'unreadable_evidence_lost:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M05','variant','unreadable_document_preserved_no_profiles','passed',true));
 event:=gen_random_uuid();

 insert into public.assistant_whatsapp_events(id,studio_id,provider,provider_event_id,phone_number_id,contact_wa_id,message_type,media_id,payload_fingerprint)
 values(event,s,'meta_whatsapp','group-'||event,'uat','99900000000','image','group-media','group-uat');
 r:=public.service_record_demi_group_receipt(s,c,g,event,'group-'||event,'group-media','UAT/group.png',repeat('a',64),15000,'MXN',0.99);
 if r->>'reason_code'<>'partial_payment_received' or (r->>'remaining_amount_minor')::integer<>15000 then raise exception 'group_amount:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','partial_amount_blocked','passed',true));
 r:=public.service_record_demi_group_receipt(s,c,g,event,'group-'||event,'group-media','UAT/group.png',repeat('a',64),15000,'MXN',0.99);
 if r->>'reason_code'<>'partial_payment_received' or (r->>'received_amount_minor')::integer<>15000 or not (r->>'idempotent')::boolean then raise exception 'partial_proof_recounted:%',r; end if;
 r:=public.service_complete_demi_group(s,c,g,people);
 if r->>'reason_code'<>'receipt_required_before_participants' or exists(select 1 from public.students where studio_id=s and phone in ('+529998880001','+529998880002')) then raise exception 'partial_created_profiles:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','partial_receipt_replay_no_profiles_or_recount','passed',true));
 r:=public.service_record_demi_group_receipt(s,c,g,event,'group-'||event,'group-media','UAT/group.png',repeat('a',64),30000,'MXN',0.99);
 if r->>'reason_code'<>'receipt_content_changed' then raise exception 'mutated_proof:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','same_document_amount_immutable','passed',true));
 event:=gen_random_uuid();
 insert into public.assistant_whatsapp_events(id,studio_id,provider,provider_event_id,phone_number_id,contact_wa_id,message_type,media_id,payload_fingerprint)
 values(event,s,'meta_whatsapp','group-'||event,'uat','99900000000','image','group-media','group-uat');
 r:=public.service_record_demi_group_receipt(s,c,g,event,'group-'||event,'group-media','UAT/group-second.png',repeat('d',64),15000,'MXN',0.99);
 if (select count(*) from public.demi_group_receipts where group_id=g and status='received')<>2 then raise exception 'separate_documents_missing'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','separate_proofs_retained_sum_to_total','passed',true));
 if not coalesce((r->>'ok')::boolean,false) then raise exception 'group_receipt:%',r; end if;
 r:=public.service_complete_demi_group(s,c,g,'[{"name":"UAT Uno","phone":"9998880001"},{"name":"UAT Dos","phone":"9998880001"}]'::jsonb);
 if r->>'reason_code'<>'duplicate_participant_phone' or exists(select 1 from public.demi_group_participants where group_id=g) then raise exception 'duplicate_phone_not_blocked:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','shared_phone_blocks_identity_merge','passed',true));
 r:=public.service_complete_demi_group(s,c,g,people);
 if not coalesce((r->>'ok')::boolean,false) or (r->>'reserved_count')::integer<>2 then raise exception 'group_complete:%',r; end if;
 if (select count(*) from public.demi_group_participants where group_id=g and reservation_id is not null)<>2 then raise exception 'group_reservations'; end if;
 if (select sum(total_minor) from public.sales where studio_id=s)<>30000 then raise exception 'group_total_duplicated'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','two_profiles_reservations_single_allocation','passed',true));
 r:=public.service_prepare_demi_group(s,c,session,2,2);
 if r->>'group_id'<>g::text or r->>'status'<>'provisional' or (r->>'payment_required')::boolean or (select count(*) from public.demi_group_bookings where studio_id=s and conversation_id=c)<>1 then raise exception 'provisional_quote_replay:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M09','variant','provisional_group_quote_replay_no_new_charge','passed',true));
 r:=public.service_complete_demi_group(s,c,g,people);
 if not coalesce((r->>'ok')::boolean,false) or (select sum(total_minor) from public.sales where studio_id=s)<>30000 then raise exception 'group_replay:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','completion_idempotent','passed',true));
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',actor)::text,true);
 r:=public.admin_review_demi_group(g,'approved','UAT proof review');
 if not coalesce((r->>'ok')::boolean,false) or (select sum(amount_minor) from public.payments where studio_id=s)<>30000 then raise exception 'group_review:%',r; end if;
 r:=public.admin_review_demi_group(g,'approved','UAT replay');
 if (select sum(amount_minor) from public.payments where studio_id=s)<>30000 then raise exception 'group_double_payment'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','review_allocations_once','passed',true));
 r:=public.service_prepare_demi_group(s,c,session,2,2);
 if r->>'group_id'<>g::text or r->>'status'<>'validated' or (r->>'payment_required')::boolean or (select count(*) from public.demi_group_bookings where studio_id=s and conversation_id=c)<>1 then raise exception 'validated_quote_replay:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M09','variant','validated_group_quote_replay_no_new_charge','passed',true));
 perform public.service_cancel_reservation(s,(select student_id from public.demi_group_participants where group_id=g and ordinal=1),(select reservation_id from public.demi_group_participants where group_id=g and ordinal=1),'UAT cancel one group reservation');
 r:=public.service_complete_demi_group(s,c,g,people);
 if (r->>'reserved_count')::integer<>1 or not exists(select 1 from jsonb_array_elements(r->'participants') p where p->>'reservation_status'='cancelled_on_time' and p->>'reservation_confirmed'='false') then raise exception 'cancelled_group_replay:%',r; end if;
 r:=public.service_prepare_demi_group(s,c,session,2,2);
 if r->>'group_id'<>g::text or (r->>'reserved_count')::integer<>1 or (r->>'reservation_confirmed')::boolean or not (r->>'existing_group_requires_review')::boolean or (select sum(amount_minor) from public.payments where studio_id=s)<>30000 then raise exception 'cancelled_group_requote:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M09','variant','cancelled_group_reservation_stays_cancelled_on_replay','passed',true));
 -- A regular student's own credit must not be charged as another trial transfer.
 c:=gen_random_uuid(); event:=gen_random_uuid();
 insert into public.assistant_conversations(id,studio_id,channel) values(c,s,'internal_demo');
 session:=(run#>>'{fixtures,sessions,alternative}')::uuid;
 r:=public.service_prepare_demi_group(s,c,session,2,1); g:=(r->>'group_id')::uuid;
 if not coalesce((r->>'ok')::boolean,false) or (r->>'amount_minor')::integer<>15000 then raise exception 'mixed_prepare:%',r; end if;
 insert into public.assistant_whatsapp_events(id,studio_id,provider,provider_event_id,phone_number_id,contact_wa_id,message_type,media_id,payload_fingerprint) values(event,s,'meta_whatsapp','mixed-'||event,'uat','99900000000','image','mixed-media','mixed-uat');
 r:=public.service_record_demi_group_receipt(s,c,g,event,'mixed-'||event,'mixed-media','UAT/mixed.png',repeat('b',64),15000,'MXN',0.99);
 people:=jsonb_build_array(jsonb_build_object('name','UAT student_active','phone',right(run#>>'{fixtures,people,student_active,phone}',10)),jsonb_build_object('name','UAT Nueva','phone','9998880003'));
 r:=public.service_complete_demi_group(s,c,g,people);
 if not coalesce((r->>'ok')::boolean,false) or (r->>'reserved_count')::integer<>2 or (r->>'allocated_minor')::integer<>15000 then raise exception 'mixed_complete:%',r; end if;
 if not exists(select 1 from public.demi_group_participants where group_id=g and student_id=(run#>>'{fixtures,people,student_active,student_id}')::uuid and allocated_minor=0 and transfer_intent_id is null and reservation_id is not null) then raise exception 'mixed_credit_charged'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','mixed_existing_credit_and_one_paid_trial','passed',true));
 r:=public.service_record_demi_group_receipt(s,c,g,event,'mixed-'||event,'mixed-media','UAT/foreign.png',repeat('a',64),15000,'MXN',0.99);
 if r->>'reason_code'<>'receipt_already_allocated' then raise exception 'foreign_document_reused:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','partial_proof_cannot_fund_another_group','passed',true));

 -- Capacity can change after receipt; keep one success and a persistent review.
 c:=gen_random_uuid(); event:=gen_random_uuid(); session:=(run#>>'{fixtures,sessions,timely}')::uuid;
 insert into public.assistant_conversations(id,studio_id,channel) values(c,s,'internal_demo');
 r:=public.service_prepare_demi_group(s,c,session,2,2);g:=(r->>'group_id')::uuid;
 insert into public.assistant_whatsapp_events(id,studio_id,provider,provider_event_id,phone_number_id,contact_wa_id,message_type,media_id,payload_fingerprint) values(event,s,'meta_whatsapp','partial-'||event,'uat','99900000000','image','partial-media','partial-uat');
 r:=public.service_record_demi_group_receipt(s,c,g,event,'partial-'||event,'partial-media','UAT/partial.png',repeat('c',64),30000,'MXN',0.99);
 update public.class_sessions set capacity=(select count(*)+1 from public.reservations where session_id=session and status='reserved') where id=session;
 r:=public.service_complete_demi_group(s,c,g,'[{"name":"UAT Parcial Uno","phone":"9998880004"},{"name":"UAT Parcial Dos","phone":"9998880005"}]'::jsonb);
 if r->>'status'<>'partial' or (r->>'reserved_count')::integer<>1 or (r->>'unallocated_minor')::integer<>15000 then raise exception 'partial_result:%',r; end if;
 if not coalesce((r->>'human_review_created')::boolean,false) or not exists(select 1 from public.assistant_handoffs where id=(r->>'handoff_id')::uuid and studio_id=s and conversation_id=c and status='open') then raise exception 'partial_handoff_claim_not_persisted:%',r; end if;
 if (select count(*) from public.demi_group_participants where group_id=g and reservation_id is not null)<>1 or not exists(select 1 from public.assistant_handoffs where studio_id=s and conversation_id=c and reason_code='group_partial' and status='open') then raise exception 'partial_oversold_or_lost_handoff'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','capacity_changed_partial_success_no_oversell_human_review','passed',true));
 if exists(select 1 from public.students where studio_id=s and phone='+529998880005') then raise exception 'failed_group_participant_became_trial'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M06','variant','failed_participant_rolls_back_trial_profile','passed',true));
 perform public.service_cancel_reservation(s,(select student_id from public.demi_group_participants where group_id=g and ordinal=1),(select reservation_id from public.demi_group_participants where group_id=g and ordinal=1),'UAT partial group cancellation');
 r:=public.service_complete_demi_group(s,c,g,'[{"name":"UAT Parcial Uno","phone":"9998880004"},{"name":"UAT Parcial Dos","phone":"9998880005"}]'::jsonb);
 if r->>'status'<>'partial' or (r->>'reserved_count')::integer<>1 or not exists(select 1 from jsonb_array_elements(r->'participants') p where p->>'reservation_status'='cancelled_on_time' and p->>'reservation_confirmed'='false') then raise exception 'partial_cancelled_replay:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('case','M09','variant','partial_retry_preserves_cancelled_slot_and_counts_only_active_reservation','passed',true));
 perform set_config('uat.group_results',out::text,true);
end $$;
select current_setting('uat.group_results')::jsonb as results;
rollback;
