begin;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
do $$
declare s uuid:='04c7022a-7340-4a60-aa66-73bd096cfcfc'; c uuid:='cc2a9e1c-01c7-442e-b281-d0ae3d1ef0ca'; g uuid:='842d61d3-8eae-4895-81de-b3779c6145c8'; r jsonb; request_id uuid; o jsonb; students_before integer; intent uuid; notification public.demi_payment_requests%rowtype; attempt integer;
begin
if not exists(select 1 from public.demi_uat_runs where studio_id=s) then raise exception 'synthetic_fixture_required'; end if;
update public.demi_mercadopago_settings set enabled=false where studio_id=s;
delete from public.demi_payment_requests where group_id=g;
select count(*) into students_before from public.students where studio_id=s;
r:=public.service_prepare_demi_mercadopago(s,c,g);
if r->>'reason_code'<>'mercadopago_disabled' then raise exception 'disabled_gate:%',r; end if;
insert into public.demi_mercadopago_settings(studio_id,enabled) values(s,true) on conflict(studio_id) do update set enabled=true;
r:=public.service_prepare_demi_mercadopago(s,c,g);
if r->>'ok'<>'true' then raise exception 'prepare:%',r; end if;
request_id:=(r->>'request_id')::uuid;
r:=public.service_prepare_demi_mercadopago(s,c,g);
if r->>'request_id'<>request_id::text or r->>'idempotent'<>'true' then raise exception 'prepare_replay:%',r; end if;
if (select count(*) from public.students where studio_id=s)<>students_before or exists(select 1 from public.demi_group_participants where group_id=g) then raise exception 'premature_identity'; end if;
r:=public.service_prepare_demi_mercadopago(s,gen_random_uuid(),g);
if r->>'reason_code'<>'group_not_found' then raise exception 'scope:%',r; end if;
r:=public.service_complete_demi_group(s,c,g,'[{"name":"UAT Pago Automático","phone":"9990000001"}]');
if r->>'reason_code'<>'receipt_required_before_participants' then raise exception 'unpaid_data:%',r; end if;
update public.demi_payment_requests set provider_order_id='UAT-ORDER-NO-PROVIDER',checkout_url='https://www.mercadopago.com.mx/checkout/UAT-NO-PAGAR' where id=request_id;
o:=jsonb_build_object('id','UAT-ORDER-NO-PROVIDER','external_reference','demi_'||request_id,'status','pending');
r:=public.service_apply_demi_mercadopago_order(request_id,o);
if r->>'status'<>'pending' or (select status from public.demi_group_bookings where id=g)<>'awaiting_receipt' then raise exception 'pending:%',r; end if;
o:=o||jsonb_build_object('status','rejected');
r:=public.service_apply_demi_mercadopago_order(request_id,o);
if r->>'status'<>'rejected' then raise exception 'rejected:%',r; end if;
o:=o||jsonb_build_object('status','processed','status_detail','accredited','total_amount','150.00','total_paid_amount','150.00','currency','MXN','transactions',jsonb_build_object('payments',jsonb_build_array(jsonb_build_object('id','UAT-PAYMENT-NO-PROVIDER','status','processed','status_detail','accredited','amount','150.00','paid_amount','150.00'))));
r:=public.service_apply_demi_mercadopago_order(request_id,o||'{"id":"WRONG"}');
if r->>'reason_code'<>'provider_identity_mismatch' then raise exception 'order_scope:%',r; end if;
r:=public.service_apply_demi_mercadopago_order(request_id,o||'{"external_reference":"WRONG"}');
if r->>'reason_code'<>'provider_identity_mismatch' then raise exception 'reference_scope:%',r; end if;
r:=public.service_apply_demi_mercadopago_order(request_id,o||'{"total_paid_amount":"149.00"}');
if r->>'reason_code'<>'provider_amount_or_currency_mismatch' then raise exception 'underpaid:%',r; end if;
r:=public.service_apply_demi_mercadopago_order(request_id,o||'{"currency":"USD"}');
if r->>'reason_code'<>'provider_amount_or_currency_mismatch' then raise exception 'currency:%',r; end if;
r:=public.service_apply_demi_mercadopago_order(request_id,jsonb_set(o,'{transactions,payments,0,status}','"pending"'));
if r->>'reason_code'<>'provider_payment_missing' then raise exception 'payment_not_approved:%',r; end if;
r:=public.service_apply_demi_mercadopago_order(request_id,o);
if r->>'status'<>'approved' or r->>'reservation_confirmed'<>'false' then raise exception 'approval:%',r; end if;
if (select count(*) from public.students where studio_id=s)<>students_before or exists(select 1 from public.demi_group_participants where group_id=g) then raise exception 'approval_does_not_invent_identity'; end if;
r:=public.service_apply_demi_mercadopago_order(request_id,o);
if r->>'idempotent'<>'true' then raise exception 'approval_replay:%',r; end if;
r:=public.service_apply_demi_mercadopago_order(request_id,jsonb_set(o,'{transactions,payments,0,id}','"WRONG-PAYMENT"'));
if r->>'reason_code'<>'provider_payment_identity_changed' then raise exception 'payment_identity:%',r; end if;
for attempt in 1..3 loop
 select * into notification from public.service_claim_demi_payment_notifications(s) where id=request_id;
 if notification.id is null or notification.notification_attempts<>attempt then raise exception 'notification_claim:%',attempt; end if;
 r:=public.service_finish_demi_payment_notification(request_id,gen_random_uuid(),true,'uat-notification',null,'UAT pago confirmado');
 if r->>'reason_code'<>'notification_lease_lost' then raise exception 'notification_lease_guard'; end if;
 r:=public.service_finish_demi_payment_notification(request_id,notification.notification_lease,false,null,'meta_429',null);
 if r->>'status'<>(case when attempt=3 then 'review' else 'pending' end) then raise exception 'notification_retry:%',r; end if;
end loop;
if exists(select 1 from public.service_claim_demi_payment_notifications(s)) then raise exception 'notification_fourth_attempt'; end if;
if not exists(select 1 from public.assistant_handoffs where conversation_id=c and status='open' and context->'payment_requests' is not null) then raise exception 'notification_handoff_refs'; end if;
update public.assistant_handoffs set status='resolved' where conversation_id=c;
update public.demi_payment_requests set notification_status='pending',notification_attempts=0 where id=request_id;
select * into notification from public.service_claim_demi_payment_notifications(s) where id=request_id;
update public.demi_payment_requests set notification_claimed_at=clock_timestamp()-interval '6 minutes' where id=request_id;
perform public.service_claim_demi_payment_notifications(s);
if not exists(select 1 from public.demi_payment_requests where id=request_id and notification_status='review' and notification_error='delivery_outcome_unknown') then raise exception 'unknown_delivery_retried'; end if;
update public.assistant_handoffs set status='resolved' where conversation_id=c;
update public.demi_payment_requests set notification_status='pending',notification_attempts=0 where id=request_id;
select * into notification from public.service_claim_demi_payment_notifications(s) where id=request_id;
r:=public.service_finish_demi_payment_notification(request_id,notification.notification_lease,true,'UAT-NOTIFICATION-ACCEPTED',null,'UAT pago confirmado');
if r->>'status'<>'sent' or not exists(select 1 from public.assistant_turns where conversation_id=c and channel_message_ref='UAT-NOTIFICATION-ACCEPTED') then raise exception 'notification_not_persisted'; end if;
r:=public.service_finish_demi_payment_notification(request_id,notification.notification_lease,true,'UAT-NOTIFICATION-ACCEPTED',null,'UAT pago confirmado');
if r->>'reason_code'<>'notification_lease_lost' or (select count(*) from public.assistant_turns where conversation_id=c and channel_message_ref='UAT-NOTIFICATION-ACCEPTED')<>1 then raise exception 'notification_replay'; end if;
r:=public.service_complete_demi_group(s,c,g,'[{"name":"UAT Pago Automático","phone":"9990000001"}]');
if r->>'status'<>'validated' or r->>'ok'<>'true' or r->>'payment_validation_required'<>'false' then raise exception 'paid_completion:%',r; end if;
select transfer_intent_id into intent from public.demi_group_participants where group_id=g;
if not exists(select 1 from public.assistant_transfer_purchase_intents i join public.payments p on p.sale_id=i.sale_id and p.reservation_id=i.reservation_id join public.product_acquisitions a on a.id=i.acquisition_id join public.class_sessions cs on cs.id=i.session_id join public.studios st on st.id=i.studio_id where i.id=intent and i.status='validated' and i.receipt_event_id is null and p.method='mercado_pago' and p.amount_minor=15000 and a.starts_on=(cs.starts_at at time zone st.timezone)::date and a.expires_on=a.starts_on+7) then raise exception 'native_finance_credit'; end if;
r:=public.service_complete_demi_group(s,c,g,'[{"name":"UAT Pago Automático","phone":"9990000001"}]');
if r->>'idempotent'<>'true' or (select count(*) from public.payments p join public.assistant_transfer_purchase_intents i on i.sale_id=p.sale_id where i.id=intent)<>1 then raise exception 'booking_replay:%',r; end if;
if has_function_privilege('anon','public.service_apply_demi_mercadopago_order(uuid,jsonb)','EXECUTE') or has_function_privilege('authenticated','public.service_activate_demi_paid_trial(uuid,uuid,uuid,uuid,uuid,integer)','EXECUTE') then raise exception 'permissions'; end if;
end $$;
select 'passed' result,24 controls,'synthetic provider data; rollback; not an external payment' scope;
rollback;
