begin;
set local request.jwt.claim.role='service_role';
set local request.jwt.claims='{"role":"service_role"}';
do $uat$
declare source uuid:='9fe23cfa-fb47-4670-afeb-ed4a56433772'; owner uuid; r jsonb; s uuid; student uuid; acquisition uuid; c uuid:=gen_random_uuid(); now_at timestamptz:=clock_timestamp(); today date; seeded integer; outcomes jsonb:='[]'; result jsonb; price integer; enrollment_price integer; sale uuid;
begin
 select user_id into owner from public.studio_memberships where studio_id=source and active and role='owner' limit 1;
 r:=public.service_create_demi_uat_run(source,owner,'recovery-conversion-uat'); s:=(r->>'studio_id')::uuid;
 select (now_at at time zone timezone)::date into today from public.studios where id=s;
 student:=(r#>>'{fixtures,people,student_expired_package,student_id}')::uuid;
 select id into acquisition from public.product_acquisitions where studio_id=s and student_id=student;
 insert into public.assistant_conversations(id,studio_id,student_id,channel) values(c,s,student,'whatsapp');
 update public.product_acquisitions set expires_on=today-1 where id=acquisition;
 seeded:=public.service_seed_due_demi_followups(s,now_at);
 if (select count(*) from public.demi_followups where studio_id=s and source_ref=acquisition::text and kind='package')<>3 or not exists(select 1 from public.demi_followups where studio_id=s and source_ref=acquisition::text and kind='package_expired') then raise exception 'package_source_not_seeded'; end if;
 if (select array_agg(extract(day from due_at-source_at)::integer order by step) from public.demi_followups where studio_id=s and source_ref=acquisition::text and kind='package')<>array[7,15,30] then raise exception 'package_recovery_schedule'; end if;
 seeded:=public.service_seed_due_demi_followups(s,now_at);
 if (select count(*) from public.demi_followups where studio_id=s and source_ref=acquisition::text)<>4 then raise exception 'package_source_doubled'; end if;
 if not exists(select 1 from public.student_enrollments where studio_id=s and student_id=student and status='active' and expires_on>today) or (select student_type::text from public.students where id=student)<>'regular' then raise exception 'expired_package_changed_student'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M14','variant','real_expired_package_sources_7_15_30_deduplicated_keep_enrollment','passed',true));
 perform set_config('request.jwt.claim.sub',owner::text,true);perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',owner)::text,true);
 select price_minor into price from public.product_templates where id=(r#>>'{fixtures,products,package}')::uuid;
 result:=public.create_student_onboarding_sale_v2(student,(r#>>'{fixtures,products,package}')::uuid,null,gen_random_uuid(),'first_usage',null,0,null,null,null,'already_active',today,null,price,'cash',today,'UAT ficticio','Renovación pagada ficticia, rollback',null,null,false,null,0,null);
 if result->>'sale_id' is null then raise exception 'package_renewal_missing:%',result; end if;
 if exists(select 1 from public.demi_followups where studio_id=s and source_ref=acquisition::text and state='pending') then raise exception 'package_renewal_not_stopped'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M14','variant','package_operation_stops_recovery','passed',true));
 -- Verify inactive attendance source without reclassifying a regular student.
 student:=(r#>>'{fixtures,people,student_active,student_id}')::uuid; c:=gen_random_uuid();
 insert into public.assistant_conversations(id,studio_id,student_id,channel) values(c,s,student,'whatsapp');
 select id into acquisition from public.product_acquisitions where studio_id=s and student_id=student;
 update public.class_sessions set starts_at=now_at-interval '15 days',ends_at=now_at-interval '15 days'+interval '1 hour' where id=(r#>>'{fixtures,sessions,past}')::uuid;
 insert into public.reservations(studio_id,student_id,session_id,acquisition_id,credits_held,status) values(s,student,(r#>>'{fixtures,sessions,past}')::uuid,acquisition,1,'attended');
 seeded:=public.service_seed_due_demi_followups(s,now_at);
 if not exists(select 1 from public.demi_followups where studio_id=s and conversation_id=c and kind='inactive' and due_at=source_at+interval '14 days') or (select student_type::text from public.students where id=student)<>'regular' then raise exception 'inactive_source'; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M14','variant','attendance_inactivity_14_days_preserves_regular_type','passed',true));
 student:=(r#>>'{fixtures,people,trial_attended,student_id}')::uuid;
 select price_minor into price from public.product_templates where id=(r#>>'{fixtures,products,package}')::uuid;
 select price_minor into enrollment_price from public.product_templates where id=(r#>>'{fixtures,products,enrollment}')::uuid;
 perform set_config('request.jwt.claim.sub',owner::text,true);perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',owner)::text,true);
 result:=public.create_student_onboarding_sale_v2(student,(r#>>'{fixtures,products,package}')::uuid,(r#>>'{fixtures,products,enrollment}')::uuid,gen_random_uuid(),'first_usage',null,0,null,null,null,'paid',today,null,price+enrollment_price,'cash',today,'UAT ficticio','Pago interno ficticio con rollback',null,null,false,null,0,null);
 sale:=(result->>'sale_id')::uuid;
 if sale is null or (select student_type::text from public.students where id=student)<>'regular' or not exists(select 1 from public.student_enrollments where studio_id=s and student_id=student and status='active') or (select coalesce(sum(amount_minor),0) from public.payments where sale_id=sale and kind='payment')<>price+enrollment_price then raise exception 'paid_conversion:%',result; end if;
 outcomes:=outcomes||jsonb_build_array(jsonb_build_object('case','M11','variant','native_paid_enrollment_and_package_promote_trial_to_regular','passed',true,'external_provider_verified',false));
 perform set_config('uat.recovery_conversion',outcomes::text,true);
end; $uat$;
select current_setting('uat.recovery_conversion')::jsonb as results;
rollback;
