begin;
set local request.jwt.claim.role='service_role';
set local request.jwt.claims='{"role":"service_role"}';
do $$
declare source uuid:='9fe23cfa-fb47-4670-afeb-ed4a56433772'; owner uuid; run jsonb; s uuid; person uuid; contact uuid; c uuid:=gen_random_uuid(); r jsonb; f public.demi_followups%rowtype; t timestamptz:=clock_timestamp(); results jsonb:='[]'; i integer; student uuid;
begin
 select user_id into owner from public.studio_memberships where studio_id=source and active and role='owner' limit 1;
 run:=public.service_create_demi_uat_run(source,owner,'followup-uat');s:=(run->>'studio_id')::uuid;
 person:=(run#>>'{fixtures,people,prospect_existing,person_id}')::uuid;
 select id into contact from public.crm_contacts where studio_id=s and person_id=person;
 insert into public.assistant_conversations(id,studio_id,channel,context) values(c,s,'internal_demo',jsonb_build_object('crm_contact_id',contact));
 r:=public.service_schedule_demi_followups(s,c,'prospect','uat-source',t);
 r:=public.service_schedule_demi_followups(s,c,'prospect','uat-source',t);
 if (select count(*) from public.demi_followups where studio_id=s)<>2 then raise exception 'followup_dedupe:%',r; end if;
 if exists(select 1 from public.demi_followups where studio_id=s and due_at<>t+step*interval '24 hours') then raise exception 'followup_interval'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('case','M04','variant','two_steps_configured_interval_idempotent','passed',true));
 select * into f from public.service_claim_demi_followups(s,t+interval '1 day',25);
 if f.id is null or f.step<>1 then raise exception 'first_claim'; end if;
 r:=public.service_finish_demi_followup(f.id,f.lease_token,true,'uat:first',null,t+interval '1 day');
 select * into f from public.service_claim_demi_followups(s,t+interval '2 days',25);
 if f.id is null or f.step<>2 then raise exception 'second_claim'; end if;
 r:=public.service_finish_demi_followup(f.id,f.lease_token,true,'uat:second',null,t+interval '2 days');
 if not exists(select 1 from public.crm_followups where studio_id=s and person_id=person and prospect_stage='not_booked' and qualification='pending') then raise exception 'silence_not_booked'; end if;
 if (select lifecycle_status from public.crm_contacts where id=contact)<>'prospect' then raise exception 'silence_type_changed'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('case','M04','variant','silence_not_booked_preserves_prospect','passed',true));
 r:=public.service_schedule_demi_followups(s,c,'prospect','uat-retry',t+interval '3 days');
 for i in 1..3 loop
  select * into f from public.service_claim_demi_followups(s,t+interval '4 days'+(i-1)*interval '5 minutes',25);
  if f.id is null then raise exception 'retry_missing:%',i; end if;
  r:=public.service_finish_demi_followup(f.id,f.lease_token,false,null,'uat_provider_failure',t+interval '4 days'+(i-1)*interval '5 minutes');
 end loop;
 if (select count(*) from public.demi_followup_attempts a join public.demi_followups j on j.id=a.followup_id where j.studio_id=s and j.source_ref='uat-retry')<>3 then raise exception 'retry_attempt_count'; end if;
 if exists(select 1 from public.service_claim_demi_followups(s,t+interval '5 days',25)) then raise exception 'fourth_attempt'; end if;
 if not exists(select 1 from public.assistant_handoffs where studio_id=s and conversation_id=c and status='open') then raise exception 'no_error_handoff'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('case','M09','variant','three_attempts_persistent_handoff_no_fourth','passed',true));
 update public.assistant_handoffs set status='resolved' where studio_id=s and conversation_id=c;
 r:=public.service_schedule_demi_followups(s,c,'prospect','uat-optout',t);
 r:=public.service_update_demi_followup_stage(s,c,'opt_out',null,null);
 if exists(select 1 from public.demi_followups where studio_id=s and state='pending') then raise exception 'optout_pending'; end if;
 if not exists(select 1 from public.person_communication_preferences where studio_id=s and person_id=person and not retention_enabled and not promotions_enabled) then raise exception 'optout_preferences'; end if;
 r:=public.service_schedule_demi_followups(s,c,'prospect','uat-optout-replay',t);
 if exists(select 1 from public.service_claim_demi_followups(s,t+interval '3 days',25)) then raise exception 'optout_send'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('case','M09','variant','optout_blocks_all_pending_and_future','passed',true));
 update public.person_communication_preferences set retention_enabled=true,promotions_enabled=true where studio_id=s and person_id=person;
 r:=public.service_update_demi_followup_stage(s,c,'not_qualified',null,null);
 if r->>'reason_code'<>'qualification_reason_required' then raise exception 'qualification_missing_reason'; end if;
 r:=public.service_update_demi_followup_stage(s,c,'not_qualified','UAT fuera de zona',null);
 r:=public.service_schedule_demi_followups(s,c,'prospect','uat-notqualified',t);
 if exists(select 1 from public.service_claim_demi_followups(s,t+interval '3 days',25)) then raise exception 'notqualified_send'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('case','M03','variant','not_qualified_requires_reason_and_stops','passed',true));

 insert into public.assistant_turns(studio_id,conversation_id,direction,role,content) values(s,c,'inbound','user','UAT vuelvo a preguntar');
 if not exists(select 1 from public.crm_followups where studio_id=s and person_id=person and qualification='pending' and qualification_reason is null) then raise exception 'reply_no_reactivation'; end if;
 r:=public.service_schedule_demi_followups(s,c,'prospect','uat-reply',t);
 select * into f from public.service_claim_demi_followups(s,t+interval '1 day',25);
 if f.id is null then raise exception 'reply_lease_setup'; end if;
 insert into public.assistant_turns(studio_id,conversation_id,direction,role,content) values(s,c,'inbound','user','UAT tengo respuesta');
 r:=public.service_revalidate_demi_followup(f.id,f.lease_token,t+interval '1 day');
 if coalesce((r->>'eligible')::boolean,false) or exists(select 1 from public.demi_followups where studio_id=s and source_ref='uat-reply' and state in ('pending','processing')) then raise exception 'reply_did_not_stop'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('case','M04','variant','reply_stops_claimed_and_pending_reactivates_notqualified','passed',true));
 insert into public.assistant_conversations(id,studio_id,channel,context) values(gen_random_uuid(),s,'whatsapp',jsonb_build_object('crm_contact_id',contact)) returning id into c;
 insert into public.assistant_turns(studio_id,conversation_id,direction,role,content) values(s,c,'outbound','assistant','UAT respuesta real persistida');
 if (select count(*) from public.demi_followups where studio_id=s and conversation_id=c and state='pending')<>2 then raise exception 'assistant_reply_no_schedule'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('case','M04','variant','assistant_reply_schedules_without_model_action','passed',true));
 update public.demi_followups set state='cancelled' where studio_id=s and person_id=person and state='pending';
 student:=(run#>>'{fixtures,people,student_active,student_id}')::uuid;
 c:=gen_random_uuid();insert into public.assistant_conversations(id,studio_id,student_id,channel) values(c,s,student,'internal_demo');
 r:=public.service_schedule_demi_followups(s,c,'enrollment','uat-enrollment',t);
 if (select array_agg(extract(day from due_at-t)::integer order by step) from public.demi_followups where studio_id=s and source_ref='uat-enrollment')<>array[7,15,30] then raise exception 'enrollment_delays'; end if;
 if exists(select 1 from public.service_claim_demi_followups(s,t+interval '7 days',25)) then raise exception 'active_enrollment_recovery'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('case','M16','variant','7_15_30_recovery_active_enrollment_stops','passed',true));
 perform set_config('uat.followup_results',results::text,true);
end $$;
select current_setting('uat.followup_results')::jsonb as results;
rollback;
