begin;
set local request.jwt.claim.role='service_role';
set local request.jwt.claims='{"role":"service_role"}';
do $$
declare actor uuid; run jsonb; s uuid; c uuid:=gen_random_uuid(); contact uuid; person uuid; session uuid; g uuid; event uuid:=gen_random_uuid(); r jsonb; people jsonb; initial_capacity integer; filler uuid; filler_reservation uuid; out jsonb:='[]';
begin
 select user_id into actor from public.studio_memberships where studio_id='9fe23cfa-fb47-4670-afeb-ed4a56433772' and active and role='owner' limit 1;
 run:=public.service_create_demi_uat_run('9fe23cfa-fb47-4670-afeb-ed4a56433772',actor,'deferred-prospect-uat'); s:=(run->>'studio_id')::uuid; session:=(run#>>'{fixtures,sessions,available}')::uuid; person:=(run#>>'{fixtures,people,prospect_existing,person_id}')::uuid;
 select id into contact from public.crm_contacts where studio_id=s and person_id=person;
 insert into public.assistant_conversations(id,studio_id,channel,context) values(c,s,'internal_demo',jsonb_build_object('crm_contact_id',contact));
 people:=jsonb_build_array(jsonb_build_object('name','UAT Primera Reserva','phone',right(run#>>'{fixtures,people,prospect_existing,phone}',10)));
 r:=public.service_prepare_demi_prospect_payment(s,c,contact,session,null);
 if not coalesce((r->>'ok')::boolean,false) or (r->>'amount_minor')::integer<>15000 then raise exception 'prepare:%',r; end if; g:=(r->>'group_id')::uuid;
 if exists(select 1 from public.students where studio_id=s and person_id=person) or exists(select 1 from public.reservations where studio_id=s and session_id=session) then raise exception 'premature_profile_or_booking'; end if;
 if (select lifecycle_status from public.crm_contacts where id=contact)<>'prospect' then raise exception 'premature_type_change'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','payment_quote_keeps_prospect_without_student_or_booking','passed',true));
 r:=public.service_prepare_demi_prospect_payment(s,c,contact,session,null);
 if r->>'group_id'<>g::text or not (r->>'idempotent')::boolean then raise exception 'quote_replay:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','quote_replay_no_duplicate_intent','passed',true));
 r:=public.service_prepare_demi_prospect_payment(s,c,gen_random_uuid(),session,null);
 if r->>'reason_code'<>'conversation_identity_mismatch' then raise exception 'identity_scope:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','different_contact_blocked','passed',true));
 r:=public.service_complete_demi_group(s,c,g,people);
 if r->>'reason_code'<>'receipt_required_before_participants' then raise exception 'before_proof:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','participant_creation_requires_proof','passed',true));
 insert into public.assistant_whatsapp_events(id,studio_id,provider,provider_event_id,phone_number_id,contact_wa_id,message_type,media_id,payload_fingerprint) values(event,s,'meta_whatsapp','single-'||event,'uat','99900000000','image','single-media','single-uat');
 r:=public.service_record_demi_group_receipt(s,c,g,event,'single-'||event,'single-media','UAT/single.png',repeat('d',64),15000,'MXN',0.99);
 if not coalesce((r->>'ok')::boolean,false) or exists(select 1 from public.students where studio_id=s and person_id=person) then raise exception 'receipt_before_data:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','matching_receipt_still_waits_for_personal_data','passed',true));
 r:=public.service_complete_demi_group(s,c,g,'[{"name":"UAT Otra Persona","phone":"9998881001"}]');
 if r->>'reason_code'<>'participant_phone_mismatch' or exists(select 1 from public.students where studio_id=s and person_id=person) then raise exception 'phone_identity:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','different_phone_cannot_replace_verified_identity','passed',true));
 select cs.capacity into initial_capacity from public.class_sessions cs where id=session;
 update public.class_sessions set capacity=1 where id=session;
 filler:=(run#>>'{fixtures,people,full_filler,student_id}')::uuid;
 r:=public.service_book_student(s,session,filler);
 select id into filler_reservation from public.reservations where studio_id=s and session_id=session and student_id=filler and status='reserved';
 if filler_reservation is null then raise exception 'capacity_fixture:%',r; end if;
 r:=public.service_complete_demi_group(s,c,g,people);
 if r->>'status'<>'partial' or exists(select 1 from public.students where studio_id=s and person_id=person) or exists(select 1 from public.assistant_conversations where id=c and student_id is not null) then raise exception 'failed_booking_changed_prospect:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','lost_capacity_does_not_create_trial_student','passed',true));
 r:=public.service_cancel_reservation(s,filler,filler_reservation,'UAT restore capacity');
 update public.class_sessions set capacity=initial_capacity where id=session;
 r:=public.service_complete_demi_group(s,c,g,people);
 if not coalesce((r->>'ok')::boolean,false) or (r->>'reserved_count')::integer<>1 then raise exception 'complete:%',r; end if;
 if (select count(*) from public.students where studio_id=s and person_id=person)<>1 or not exists(select 1 from public.assistant_conversations ac join public.students st on st.id=ac.student_id where ac.id=c and st.person_id=person and st.student_type='trial') then raise exception 'link_or_type_missing'; end if;
 if (select sum(total_minor) from public.sales where studio_id=s)<>15000 or exists(select 1 from public.payments where studio_id=s) then raise exception 'provisional_financial_state'; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','proof_and_data_create_one_trial_booking_and_link_conversation','passed',true));
 perform set_config('request.jwt.claim.sub',actor::text,true); perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',actor)::text,true);
 r:=public.admin_review_demi_group(g,'approved','UAT single proof review');
 r:=public.admin_review_demi_group(g,'approved','UAT replay');
 r:=public.service_complete_demi_group(s,c,g,people);
 if not coalesce((r->>'ok')::boolean,false) or (select sum(amount_minor) from public.payments where studio_id=s)<>15000 or (select sum(total_minor) from public.sales where studio_id=s)<>15000 then raise exception 'review_replay:%',r; end if;
 out:=out||jsonb_build_array(jsonb_build_object('variant','validation_and_replay_charge_once','passed',true));
 perform set_config('uat.deferred_results',out::text,true);
end $$;
select current_setting('uat.deferred_results')::jsonb as results;
rollback;
