begin;
set local role service_role;
set local request.jwt.claims='{"role":"service_role"}';
set local request.jwt.claim.role='service_role';
do $$
declare source uuid:='9fe23cfa-fb47-4670-afeb-ed4a56433772'; owner uuid; run jsonb; s uuid; c uuid:=gen_random_uuid(); i uuid:=gen_random_uuid();
 contact uuid; person uuid; st uuid; session uuid; h uuid; r jsonb; results jsonb:='[]'; n integer;
begin
 select user_id into owner from public.studio_memberships where studio_id=source and role='owner' and active limit 1;
 run:=public.service_create_demi_uat_run(source,owner,'identity-uat'); s:=(run->>'studio_id')::uuid;
 person:=(run#>>'{fixtures,people,prospect_existing,person_id}')::uuid;
 st:=(run#>>'{fixtures,people,student_active,student_id}')::uuid;
 session:=(run#>>'{fixtures,sessions,available}')::uuid;
 select id into contact from public.crm_contacts where studio_id=s and person_id=person;
 insert into public.assistant_channel_identities(id,studio_id,provider,provider_account_id,provider_contact_id,person_id,crm_contact_id) values(i,s,'facebook_messenger','11111','22222',person,contact);
 insert into public.assistant_conversations(id,studio_id,channel,external_thread_ref,context) values(c,s,'facebook_messenger','11111:22222',jsonb_build_object('identity_id',i,'crm_contact_id',contact,'provider_account_id','11111','provider_contact_id','22222'));
 insert into public.assistant_turns(studio_id,conversation_id,direction,role,content) values(s,c,'inbound','user','Historial UAT antes de verificar');
 r:=public.service_prepare_demi_prospect_payment(s,c,contact,session);
 if r->>'reason_code'<>'minimal_phone_identification_required' or exists(select 1 from public.demi_group_bookings where conversation_id=c) then raise exception 'payment_before_minimal_identity:%',r; end if;
 r:=public.service_prepare_demi_group(s,c,session,1,1);
 if r->>'reason_code'<>'minimal_phone_identification_required' then raise exception 'group_payment_before_identity:%',r; end if;
 results:=results||jsonb_build_array(jsonb_build_object('variant','payment_paths_require_minimal_identity','passed',true));
 r:=public.service_identify_demi_meta_contact(s,c,'123');
 if r->>'reason_code'<>'phone_requires_ten_digits' or (select metadata from public.assistant_channel_identities where id=i) ? 'claimed_phone' then raise exception 'invalid_phone_written'; end if;
 r:=public.service_identify_demi_meta_contact(s,c,'9999999999');
 if r->>'reason_code'<>'phone_requires_ten_digits' then raise exception 'fictitious_phone'; end if;
 r:=public.service_identify_demi_meta_contact(s,c,'+52 999 888 9091');
 if r->>'minimal_identification_completed'<>'true' or r->>'identity_verified'<>'false' then raise exception 'minimal_new_phone:%',r; end if;
 if exists(select 1 from public.person_contacts where studio_id=s and value='+529998889091') then raise exception 'claim_is_authoritative_phone'; end if;
 r:=public.service_identify_demi_meta_contact(s,c,'9998889091');
 if r->>'ok'<>'true' then raise exception 'repeated_lada:%',r; end if;
 results:=results||jsonb_build_array(jsonb_build_object('variant','invalid_rejected_mexican_number_normalized_unverified_claim_only','passed',true));
 r:=public.service_check_demi_minimal_identity(source,c);
 if r->>'ok'<>'false' then raise exception 'foreign_conversation'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('variant','cross_studio_denied','passed',true));
 select count(*) into n from public.students where studio_id=s;
 r:=public.service_identify_demi_meta_contact(s,c,(select phone from public.students where id=st));
 if r->>'reason_code'<>'identity_verification_required' or r->>'human_review_created'<>'true' or r ? 'student_id' or r ? 'full_name' then raise exception 'existing_phone_exposed_or_linked:%',r; end if;
 h:=(r->>'handoff_id')::uuid;
 if (select student_id from public.assistant_conversations where id=c) is not null then raise exception 'unverified_student_link'; end if;
 if not exists(select 1 from public.assistant_handoffs where id=h and status='open' and context#>'{identity_verification,candidate_person_ids}' @> jsonb_build_array((select person_id from public.students where id=st))) then raise exception 'identity_case_refs_missing'; end if;
 if (select count(*) from public.students where studio_id=s)<>n then raise exception 'duplicate_profile'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('variant','existing_phone_real_human_no_pii_no_auto_link','passed',true));
 perform set_config('uat.identity_studio',s::text,true); perform set_config('uat.identity_owner',owner::text,true);
 perform set_config('uat.identity_handoff',h::text,true); perform set_config('uat.identity_conversation',c::text,true);
 perform set_config('uat.identity_student',st::text,true); perform set_config('uat.identity_count',n::text,true);
 perform set_config('uat.identity_results',results::text,true);
end $$;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',current_setting('uat.identity_owner'))::text,true);
select set_config('request.jwt.claim.sub',current_setting('uat.identity_owner'),true);
set local request.jwt.claim.role='authenticated';
do $$
declare s uuid:=current_setting('uat.identity_studio')::uuid; h uuid:=current_setting('uat.identity_handoff')::uuid; c uuid:=current_setting('uat.identity_conversation')::uuid;
 st uuid:=current_setting('uat.identity_student')::uuid; p uuid; r jsonb; results jsonb:=current_setting('uat.identity_results')::jsonb;
begin
 select person_id into p from public.students where id=st and studio_id=s;
 r:=public.admin_verify_demi_channel_identity(s,h,p,'in_person','Identidad confirmada presencialmente en UAT');
 if r->>'reason_code'<>'claim_identity_case_first' then raise exception 'unclaimed_identity_case:%',r; end if;
 r:=public.admin_claim_demi_handoff(s,h);
 r:=public.admin_verify_demi_channel_identity(s,h,gen_random_uuid(),'in_person','Identidad confirmada presencialmente en UAT');
 if r->>'reason_code'<>'identity_candidate_mismatch' then raise exception 'wrong_candidate:%',r; end if;
 r:=public.admin_verify_demi_channel_identity(s,h,p,'in_person','x');
 if r->>'reason_code'<>'verification_evidence_required' then raise exception 'missing_evidence:%',r; end if;
 r:=public.admin_verify_demi_channel_identity(s,h,p,'in_person','Identidad confirmada presencialmente en UAT');
 if r->>'ok'<>'true' or r->>'profile_created'<>'false' then raise exception 'verified_link:%',r; end if;
 if (select student_id from public.assistant_conversations where id=c)<>st then raise exception 'wrong_link'; end if;
 if not exists(select 1 from public.assistant_turns where conversation_id=c and content='Historial UAT antes de verificar') then raise exception 'history_lost'; end if;
 r:=public.admin_verify_demi_channel_identity(s,h,p,'in_person','Identidad confirmada presencialmente en UAT');
 if r->>'idempotent'<>'true' or (select count(*) from public.demi_identity_link_audit where handoff_id=h)<>1 then raise exception 'identity_replay'; end if;
 if (select count(*) from public.students where studio_id=s)<>current_setting('uat.identity_count')::integer then raise exception 'new_student_created'; end if;
 results:=results||jsonb_build_array(jsonb_build_object('variant','staff_claim_candidate_evidence_required_verified_link_audit_once_history_preserved','passed',true));
 r:=public.admin_resolve_demi_handoff(s,h,'Verificación UAT completada; reanudar identidad existente');
 if r->>'ok'<>'true' then raise exception 'identity_resume:%',r; end if;
 results:=results||jsonb_build_array(jsonb_build_object('variant','verified_identity_case_resolves_and_resumes','passed',true));
 perform set_config('uat.identity_results',results::text,true);
end $$;
select current_setting('uat.identity_results')::jsonb as results;
rollback;
